- name: Backup_list
  ansible.builtin.shell: |
    export RESTIC_REPOSITORY="{{ restic_backup_jobs_s3_repo }}"
    export AWS_ACCESS_KEY_ID="{{ restic_backup_jobs_s3_repo_access_key }}"
    export AWS_SECRET_ACCESS_KEY="{{ restic_backup_jobs_s3_repo_secret_key }}"
    export RESTIC_PASSWORD="{{ restic_backup_jobs_s3_repo_password }}"
    restic snapshots --tag "{{ item.name }}"
  register: backup_list_result
  loop: "{{ restic_backup_jobs }}"
  
- name: Debug backup_list_result
  ansible.builtin.debug:
    msg: "{{ item.stdout }}"
  loop: "{{ backup_list_result.results }}"
...
