---
- name: Restore
  ansible.builtin.shell: |
    export RESTIC_REPOSITORY="{{ restic_backup_jobs_s3_repo }}"
    export AWS_ACCESS_KEY_ID="{{ restic_backup_jobs_s3_repo_access_key }}"
    export AWS_SECRET_ACCESS_KEY="{{ restic_backup_jobs_s3_repo_secret_key }}"
    export RESTIC_PASSWORD="{{ restic_backup_jobs_s3_repo_password }}"
    {% if item.dirs is defined %}
    {% if item.dirs | length > 0 %}
    {% for dir in item.dirs %}
    /usr/local/bin/restic -v restore {{ restic_restore_snapshot | default('latest') }} \
    --target "{{ dir }}_restored" \
    --include "{{ dir }}" \
    --path "{{ dir }}"


    if [ -d "{{ dir }}" ]
    then
      mv "{{ dir }}" "{{ dir }}.old" 
    fi

    mv "{{ dir }}_restored/{{ dir[1:] }}" "{{ dir }}"

    if [ -d "{{ dir }}_restored" ]
    then
      rm -rf "{{ dir }}_restored"
    fi

    if [ -d "{{ dir }}.old" ]
    then
      rm -rf "{{ dir }}.old"
    fi
    {% endfor %}
    {% endif %}
    {% endif %}
  register: restore_result
  loop: "{{ restic_backup_jobs }}"

- name: Restore - debug
  ansible.builtin.debug:
    msg: '{{ item.stdout }}'
  loop: "{{ restore_result.results }}"
...
